### ISSUE TITLE
Setup keycloak for production mode

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#105]
To run keycloak in production mode (by switching from `start-dev` to `start` in docker-compose.yml) we need to change command line arguments and environmental variables.

**The following is not correct**, but putting it here as a reminder of some of the variables that might need to be tweaked:

```
      command:
        - start-dev
        - --optimized
#        - --auto-build
        - --http-relative-path /keycloak
        - --import-realm
      environment:
        KC_HOSTNAME: localhost
        KC_PROXY_ADDRESS_FORWARDING: true
        KC_HOSTNAME_STRICT_HTTPS: false
        KC_HOSTNAME_STRICT: false
        KC_PROXY: edge
        KC_HTTP_ENABLED: true
```
