### ISSUE TITLE
Upload file is slow on https://clowder2.software-dev.ncsa.cloud/

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#312]
This might due to the storage class nfs-taiga we are using for minio

**Comment by longshuicy** [comment]
I think I know what to do:

overwrite in the values to use csi-cinder-sc-retain

```

minio:
  auth:
    rootUser: clowder
    rootPassword: ilikecats
  persistence:
    storageClass: csi-cinder-sc-retain
    size: 20Gi
  ingress:
    hostname: minio.clowder2.software-dev.ncsa.cloud
  apiIngress:
    hostname: minio.clowder2.software-dev.ncsa.cloud

```

@robkooper @lmarini could you confirm?
