### ISSUE TITLE
DevOps improvement using initial containers

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#943]
- Extractors add check for "if Rabbimtq is alive"
- Backend check "if certain URL e.g keycloak is alive"

Some of the example see here:
https://github.com/IN-CORE/incore-helm/blob/develop/templates/auth/deployment.yaml#L28
https://github.com/ncsa/checks
```
initContainers:
        - name: check-url
          image: "ncsa/checks:1.0.0"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: URL
              {{- with first .Values.keycloak.ingress.rules }}
              value: {{ printf "https://%s/auth/realms/%s/" .host $.Values.auth.realm | quote }}
              {{- end }}
```
If I don’t want to check something remove it from the initContainers list
